### ISSUE TITLE
train drums data error

### ISSUE THREAD

**Issue by eternalland** [ingra14m/Specular-Gaussians#13]
when i execute this instruction  "python train_anchor.py -s data/nerf_synthetic/drums -m outputs/nerf/drums --eval --voxel_size 0.001 --update_init_factor 4 --iterations 30_000", it show following error:

Traceback (most recent call last):
  File "train_anchor.py", line 492, in <module>
    args.checkpoint_iterations, args.start_checkpoint, args.debug_from, logger)
  File "train_anchor.py", line 53, in training
    dataset.update_init_factor, dataset.update_hierachy_factor)
  File "/home/mayu/postg/thesis/Spec-Gaussian/Spec-Gaussian/scene/anchor_gaussian_model.py", line 96, in __init__
    self.mlp_color = AnchorSpecularNetwork(feature_dims=feat_dim).cuda()
  File "/home/mayu/postg/thesis/Spec-Gaussian/Spec-Gaussian/utils/spec_utils.py", line 254, in __init__
    self.render_module = ASGRender(self.asg_hidden, 2, 2, 64, num_theta=2, num_phi=4)
TypeError: __init__() got multiple values for argument 'num_theta'

**Comment by ingra14m** [comment]
Hi, thanks for your interest.

sry for that errors in training anchor Gaussian. I have committed new code (not tested yet) to fix the bug. This problem stems from the inconsistent ASG appearance field of anchor Gaussian and the version without anchor.

Since I mainly tested the performance on the version without anchor, I recommend you to use the same one! In the latest paper (not updated on arxiv yet), the anchor Gaussian is only a version to accelerate, with an obvious gap with the version without anchor.
