### ISSUE TITLE
how can i further produce 3d panoramic view

### ISSUE THREAD

**Issue by eternalland** [ingra14m/Specular-Gaussians#14]
I am extremely grateful for your work. Now that running and training these codes has resulted in the generation of rendered images, depth maps, normal maps, and point clouds, could you kindly guide me on how I can further produce a 3D panoramic view? Thank you!

**Comment by ingra14m** [comment]
Hi, thanks for your interest and sorry for the late reply.

From my perspective, I think that you wanna see the rendering results from any viewpoint after training.

You can use `python render.py -m your/path/to/model --mode video`

**Comment by eternalland** [comment]
> Hi, thanks for your interest and sorry for the late reply.
> 
> From my perspective, I think that you wanna see the rendering results from any viewpoint after training.
> 
> You can use `python render.py -m your/path/to/model --mode video`

@ingra14m 
Thanks very much for your answer. But after I input "python render.py -m ~/postg/thesis/Spec-Gaussian/Spec-Gaussian/outputs/nerf/drums --mode video", it displays this following error. Does this attribute exist in the .ply ? 

> Looking for config file in /home/mayu/postg/thesis/Spec-Gaussian/Spec-Gaussian/outputs/nerf/drums/cfg_args
Config file found: /home/mayu/postg/thesis/Spec-Gaussian/Spec-Gaussian/outputs/nerf/drums/cfg_args
Rendering /home/mayu/postg/thesis/Spec-Gaussian/Spec-Gaussian/outputs/nerf/drums
Loading trained model at iteration 30000 [29/09 21:58:09]
Found transforms_train.json file, assuming Blender data set! [29/09 21:58:09]
Reading Training Transforms [29/09 21:58:09]
Reading Test Transforms [29/09 21:58:13]
Loading Training Cameras [29/09 21:58:21]
Loading Test Cameras [29/09 21:58:23]
Traceback (most recent call last):
  File "render.py", line 215, in <module>
    args.skip_test, args.mode)
  File "render.py", line 169, in render_sets
    scene = Scene(dataset, gaussians, load_iteration=iteration, shuffle=False)
  File "/home/1/postg/thesis/Spec-Gaussian/Spec-Gaussian/scene/__init__.py", line 97, in __init__
    og_number_points=len(scene_info.point_cloud.points))
  File "/home/1/postg/thesis/Spec-Gaussian/Spec-Gaussian/scene/gaussian_model.py", line 211, in load_ply
    features_dc[:, 0, 0] = np.asarray(plydata.elements[0]["f_dc_0"])
  File "/home/1/anaconda3/envs/spec-gaussian-env/lib/python3.7/site-packages/plyfile.py", line 827, in __getitem__
    return self.data[key]
  File "/home/1/anaconda3/envs/spec-gaussian-env/lib/python3.7/site-packages/numpy/core/memmap.py", line 334, in __getitem__
    res = super().__getitem__(index)
ValueError: no field of name f_dc_0

![image](https://github.com/user-attachments/assets/2b20a49f-7678-459a-9f1d-e7aff3c4aca3)
![image](https://github.com/user-attachments/assets/470eed1d-fcbf-4432-9af0-4013cf0e1f9b)
![image](https://github.com/user-attachments/assets/db57cfa7-3360-4981-84b3-57546bd0adbe)
